name: Diff-Report

on: 
  pull_request:
    types: [opened, reopened, synchronize, edited]
  issue_comment:
    types: [created]

jobs:
  make_report:
    if: (github.event_name == 'pull_request') || (github.event_name == 'issue_comment' && github.event.comment.body == 'report')
    runs-on: ubuntu-latest

    steps:        
     - name: Issue action
       if: github.event_name == 'issue_comment'
       run: |
        echo "${{github.event.issue.body}}" > text
        echo "${{github.event.issue.user.login}}" > user
       
     - name: PR action
       if: github.event_name == 'pull_request'
       run: |
        echo "${{github.event.pull_request.body}}" > text
        echo "${{github.event.pull_request.user.login}}" > user

     - name: Set username to outputs
       id: setUser
       run: echo ::set-output name=pr_creator::$(cat user)
    
     - name: Parse body
       id: parse
       run: |
        grep "^Diff Regression projects:" text > temp || echo "No diff regression projects found"
        sed 's/Diff Regression projects: //' temp > proj || echo "" > proj
        grep "^Diff Regression config:" text > temp || echo "No diff regression congig found"
        sed 's/Diff Regression config: //' temp > config || echo "" > config
        cat proj
        cat config
        
     - name: show info
       run: echo '${{steps.setUser.outputs.pr_creator}}'
#       run: echo "${{toJSON(github.event)}}"
