name: Diff-Report

on: 
  pull_request:
    types: [opened, reopened, synchronize, edited]
  issue_comment:
    types: [created]
env:
  pr_body: ${{ github.event.pull_request.body }}
  issue_body: ${{github.event.issue.body}}

jobs:
  make_report:
    if: (github.event_name == 'pull_request') || (github.event_name == 'issue_comment' && github.event.comment.body == 'report')
    runs-on: ubuntu-latest

    steps:        
     - name: Issue action
       if: github.event_name == 'issue_comment'
       run: |
        echo "${{github.event.issue.body}}" > text
        echo "${{github.event.issue.user.login}}" > user
       
     - name: PR action
       if: github.event_name == 'pull_request'
       run: |
        echo "${{github.event.pull_request.body}}" > text
        echo "${{github.event.pull_request.user.login}}" > user

     - name: show result
       id: setUser
       run: |
         cat text
         cat user
         run: echo ::set-output name=pr_creator::$(cat user)
        
        
     - name: show info
       run: echo '${{steps.setUser.outputs.pr_creator}}'
#       run: echo "${{toJSON(github.event)}}"
