name: Diff-Report

on: 
  pull_request:
    types: [opened, reopened, synchronize, edited]
  issue_comment:
    types: [created]

jobs:
  parse_body:
    if: (github.event_name == 'pull_request') || (github.event_name == 'issue_comment' && github.event.comment.body == 'report')
    runs-on: ubuntu-latest
    outputs:
      proj_link: ${{ steps.parse.outputs.proj_link }}
      config_link: ${{ steps.parse.outputs.config_link }}
      user: ${{ steps.branch.outputs.user }}
      branch: ${{ steps.branch.outputs.ref }}
      
    steps:
#        echo "${{ toJson(github) }}"
     - name: Test Mercurial
       run: |
         sudo apt-get install mercurial
         mercurial -version
       
     - name: Issue comment action
       if: github.event_name == 'issue_comment'
       run: |
        echo "${{github.event.issue.body}}" > text
        echo "${{github.event.issue.user.login}}" > user
        wget -q ${{github.event.issue.pull_request.url}} -O info.json
        jq .head.ref info.json > branch
       
     - name: PR action
       if: github.event_name == 'pull_request'
       run: |
        echo "${{github.event.pull_request.body}}" > text
        echo ${{github.event.pull_request.user.login}} > user
        echo ${{github.event.pull_request.head.ref}} > branch

     - name: Parse body
       id: parse
       run: |
        grep "^Diff Regression projects:" text > temp || echo "fail" > temp
        sed 's/Diff Regression projects: //' temp > proj
        echo ::set-output name=proj_link::$(cat proj)
        grep "^Diff Regression config:" text > temp || echo "fail" > temp
        sed 's/Diff Regression config: //' temp > config
        echo ::set-output name=config_link::$(cat config)
        
     - name: Set branch and head_label
       id: branch
       run: |
        echo ::set-output name=user::$(cat user)
        echo ::set-output name=ref::$(cat branch)
      
     - name: info
       run: |
        cat user
        cat branch
        echo ${{steps.branch.outputs.ref}}
        echo ${{steps.branch.outputs.user}}
  
  make_report:
    runs-on: ubuntu-latest
    needs: parse_body
    if: (needs.parse_body.outputs.proj_link != 'fail') && (needs.parse_body.outputs.config_link != 'fail')
    steps:
      - name: Download files
        run: |
         wget -q ${{needs.parse_body.outputs.proj_link}} -O proj.properties
         wget -q ${{needs.parse_body.outputs.config_link}} -O config.xml
      
      - name: Get branch and user
        uses: actions/checkout@v2
        with:
         repository: ${{needs.parse_body.outputs.user}}/Test_Git_Action
         ref: master
         fetch-depth: 0
         path: dir
          
      - name: show info
        run: |
         echo ${{needs.parse_body.outputs.user}}
         echo ${{needs.parse_body.outputs.branch}}
        
      - name: Message
        id: out
        run: |
         echo "Diff Report ..." > message
         echo ::set-output name=message::$(cat message)
      
      - name: Comment PR
        uses:  kate2513/javascript-test-action@master 
        with:
         message: ${{steps.out.outputs.message}}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
